USE [master]
GO

/****** Object:  Database [DBCRUDE]    Script Date: 6/07/2024 8:43:32 p. m. ******/
CREATE DATABASE [DBCRUDE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBCRUDE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLMIO\MSSQL\DATA\DBCRUDE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBCRUDE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLMIO\MSSQL\DATA\DBCRUDE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBCRUDE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBCRUDE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBCRUDE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBCRUDE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBCRUDE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBCRUDE] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBCRUDE] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DBCRUDE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBCRUDE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBCRUDE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBCRUDE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBCRUDE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBCRUDE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBCRUDE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBCRUDE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBCRUDE] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DBCRUDE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBCRUDE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBCRUDE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBCRUDE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBCRUDE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBCRUDE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBCRUDE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBCRUDE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBCRUDE] SET  MULTI_USER 
GO

ALTER DATABASE [DBCRUDE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBCRUDE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBCRUDE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBCRUDE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBCRUDE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBCRUDE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBCRUDE] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBCRUDE] SET  READ_WRITE 
GO


